package it.polimi.ingsw.controller;

public enum Action {
    ADDME, PLAYCARD, MOVESTUDENT, MOVEMOTHERNATURE, SELECTCLOUD, SHOWME, USEPOWER, ACTIVECARD,
    EXCHANGESTUDENT, BLOCK_ISLAND, BLOCK_COLOR, PUT_BACK, ISLAND_INFLUENCE
}